config/routes.rb
Berkeleygag::Application.routes.draw do
  root to:"home#index"

  resources :users
  resources :sessions
  resources :posts do
    member {post :vote}
  end

  get "signup", to:"users#new"
  get "signin", to:"sessions#new"
  get "signout", to:"sessions#destroy"
 
  get "confirm/:token", to:"users#confirm"
  get "access_denied", to:"home#access_denied"

  get "haha", to:"home#haha"
  get "meh", to:"home#meh"

  get "about", to:"static_pages#about"
  get "contact", to:"static_pages#contact"
  get "terms", to: "static_pages#terms"


  match "*gibberish", to:"home#not_found"
end

app/views/layouts/_footer.html.erb
  <footer class="navbar navbar-default">
    <div class="container">
      <small class="navbar-brand slogan">
        <a href="http://berkeleygag.com/">BerkeleyGag</a>
        <span>by Alexander Vasyuk</span>
      </small>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation" id="top-menu">
	<div class="container">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		    <span class="sr-only">Toggle navigation</span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>	
		    <span class="icon-bar"></span>
		  </button>
		  <%= link_to "BerkeleyGag", root_url, class: "navbar-brand" %>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
      	<%= tag(:li, class: "divider-vertical")%>
      	<%= content_tag(:li, link_to("New", root_path)) %>
		<%= tag(:li, class: "divider-vertical")%>
		<%= content_tag(:li, link_to("Haha", haha_path)) %>
		<%= tag(:li, class: "divider-vertical")%>
		<%= content_tag(:li, link_to("Meh", meh_path)) %>
      </ul> 

      <ul class="nav navbar-nav navbar-right">
      	  <% if signed_in? %>
			<%= content_tag(:li, link_to("#{current_user.email}", user_path(current_user))) %>
			<%= tag(:li, class: "divider-vertical")%>
			<li><%= link_to "About", about_path %></li>
			<%= tag(:li, class: "divider-vertical")%>
			<li><%= link_to "Terms", terms_path %></li>
			<%= tag(:li, class: "divider-vertical")%>
			<%= content_tag(:li, link_to("Sign out", signout_path))%>
          <% else %>
            <%= tag(:li, class: "divider-vertical")%>
            <li><%= link_to "About", about_path %></li>
            <%= tag(:li, class: "divider-vertical")%>
            <li><%= link_to "Terms", terms_path %></li>
            <%= tag(:li, class: "divider-vertical")%>
            <%= content_tag(:li, link_to("Sign in", signin_path))%>
            <%= tag(:li, class: "divider-vertical")%>
            <%= content_tag(:li, link_to("Sign up", signup_path))%>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Berkeley Gag</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
      <%= render "layouts/header"%>
      <div id="content">
        <div class="container">
              <% flash.each do |key,value| %>
                <div class="<%= flash_class(key) %>">
                  <%= value %>
                </div>
              <% end %>

              <%= yield %> 
            </div>
        </div>
      <%= render "layouts/footer"%>
    </div>  
  <%= render "shared/google_analytics"%>
</body>
</html>